# Generated by Django 5.2 on 2025-05-05 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLogSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('driver_number', models.CharField(max_length=20)),
                ('driver_initials', models.CharField(max_length=10)),
                ('co_driver_name', models.CharField(blank=True, max_length=255, null=True)),
                ('total_miles', models.PositiveIntegerField()),
                ('vehicle_number', models.CharField(max_length=50)),
                ('shipper_name', models.CharField(max_length=255)),
                ('commodity', models.CharField(max_length=255)),
                ('load_number', models.CharField(max_length=100)),
                ('home_address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ELDLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('Off Duty', 'Off Duty'), ('Sleeper Berth', 'Sleeper Berth'), ('Driving', 'Driving'), ('On Duty (Not Driving)', 'On Duty (Not Driving)')], max_length=50)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eld_entries', to='trip_api.dailylogsheet')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('cycle_hours_used', models.PositiveIntegerField(help_text='Hours used in the 70-hour cycle')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dailylogsheet',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='trip_api.trip'),
        ),
    ]
