# Generated by Django 5.2 on 2025-05-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailylogsheet',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
