# Generated by Django 5.2 on 2025-05-05 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='dropoff_location',
        ),
    ]
