# Generated by Django 5.2 on 2025-05-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_api', '0002_alter_dailylogsheet_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eldlogentry',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
